spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: 'https://github.com/iddefranco/controle-financeiro-repo'
server:
  port: 8888

